# Generated by Django 5.0.7 on 2024-11-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=5),
        ),
    ]
